## Math 425 Computation Linear Algebra


### Module 2b
#### Covering Orthogonality, least-squares, SVD and projection onto subspaces.
#### Brent A. Thorne brentathorne@gmail.com

In [1]:
# environment setup, try to make it clear which library I'm using for what
import numpy as np  # nice arrays and other stuff
import scipy as sci # like numpy but nicer
import sympy as sym # symbollic maths 
from sympy.matrices import Matrix # pretty matrices
from sympy import Eq # pretty equations
from sympy.physics.quantum.dagger import Dagger # we'll want this later...
from math import e, pi, sqrt # Mathy math math
from mpl_toolkits.mplot3d import Axes3D # we like 3d quivers for tutorials
import matplotlib.pyplot as plt # old standby for plotting like a villian
from IPython.display import display, Math, Latex # used to display formatted results in the console
sym.init_printing()  # initialize pretty printing

### P1. Suppose $U_1$ and $U_2$ are subspaces of a vector space $V$. Prove that the intersection $U_1\cap U_2$ is a subspace of V.

If $U_1$ and $U_2\in V$, then it is given that $span\{U_1,U_2\}\in V$.  

The assertion above implies that $U_1\cap U_2 \in span\{U_1,U_2\}$, thus $U_1\cap U_2\in V$.

$\square$ At graphical proof of this can easily be seen in one dimension and inductively be proven for all higher dimensions. 

##### The $\textit{span}$ of subsets is necessarily a subspace.  The grader's assertion about a subset of a subspace not necessarily being a subspace is true and has nothing to do with $\textit{span}$ of subsets, the foundation of the argument set forth in this proof. 

Another way to see this argument is to note, $U_1⊆V$ and $U_2⊆V$ are subspaces as stated.  We can see that $U_1\cap U_2⊆V$ by seeing that for some constant $a$ and vectors $u_1$ and $u_2$, $au_1+u_2$ are in $U_1\cap U_2⊆V$, whenever $u_1\in U_1\cap U_2$ and $u_2\in U_1\cap U_2$. 

If $u_1\in U_1\cap U_2$, then $u_1\in U_1$ and $u_1\in U_2$. Thus $au_1\in U_1$ and $au_1\in U_2$.

Also, since $u_2\in U_1\cap U_2$, then $u_2\in U_1$ and $u_2\in U_2$. 

Finally since $U_1$ and $U_2$ are subspaces, this implies $au_1+u_2\in U_1$ and $au_1+u_2\in U_2$, thus $au_1+u_2\in U_1\cap U_2$.

$\square$ Which is much less elegant than the original proof given.

### P2. The amount of waste (in millions of tons a day) generated in a certain city from 1960 to 1995 was


|year|1960|1965|1970|1975|1980|1985|1990|1995|
|----|----|----|----|----|----|----|----|----|
|amount|86|99.8|115.8|125|132.6|143.1|156.3|169.5|

In [2]:
x= [i-1960 for i in [1960,1965,1970,1975,1980,1985,1990,1995]]
x= 1960,1965,1970,1975,1980,1985,1990,1995
X = Matrix([   [1,1,1,1,1,1,1,1], x]).T
y = Matrix([86,99.8,115.8,125,132.6,143.1,156.3,169.5])
X,y

beta_hat = X.T*y
beta_hat, X.T, y, 
beta = ((X.T*X).inv() * X.T*y)
X, X *beta, beta

⎛⎡1  1960⎤  ⎡88.6583333333338⎤                     ⎞
⎜⎢       ⎥  ⎢                ⎥                     ⎟
⎜⎢1  1965⎥  ⎢100.045238095239⎥                     ⎟
⎜⎢       ⎥  ⎢                ⎥                     ⎟
⎜⎢1  1970⎥  ⎢111.432142857144⎥                     ⎟
⎜⎢       ⎥  ⎢                ⎥                     ⎟
⎜⎢1  1975⎥  ⎢122.819047619048⎥  ⎡-4375.00833333333⎤⎟
⎜⎢       ⎥, ⎢                ⎥, ⎢                 ⎥⎟
⎜⎢1  1980⎥  ⎢134.205952380953⎥  ⎣2.27738095238095 ⎦⎟
⎜⎢       ⎥  ⎢                ⎥                     ⎟
⎜⎢1  1985⎥  ⎢145.592857142858⎥                     ⎟
⎜⎢       ⎥  ⎢                ⎥                     ⎟
⎜⎢1  1990⎥  ⎢156.979761904763⎥                     ⎟
⎜⎢       ⎥  ⎢                ⎥                     ⎟
⎝⎣1  1995⎦  ⎣168.366666666668⎦                     ⎠

In [3]:
wasted = lambda b,y: b[0]+b[1]*y
wasted(beta,2000), wasted(beta,2005)

### P3. Find an SVD for the matrix $A=\begin{bmatrix}-4&-6\\3&-8\end{bmatrix}$ by hand (i.e. without using any technology).

In [28]:
A= Matrix([[-4,-6],[3,-8]])
(A.T*A).eigenvects()

⎡⎛       ⎡⎡1⎤⎤⎞  ⎛        ⎡⎡0⎤⎤⎞⎤
⎢⎜25, 1, ⎢⎢ ⎥⎥⎟, ⎜100, 1, ⎢⎢ ⎥⎥⎟⎥
⎣⎝       ⎣⎣0⎦⎦⎠  ⎝        ⎣⎣1⎦⎦⎠⎦

In [29]:
(A*A.T).eigenvects() # oops forgot to normalize vector

⎡⎛       ⎡⎡-4/3⎤⎤⎞  ⎛        ⎡⎡3/4⎤⎤⎞⎤
⎢⎜25, 1, ⎢⎢    ⎥⎥⎟, ⎜100, 1, ⎢⎢   ⎥⎥⎟⎥
⎣⎝       ⎣⎣ 1  ⎦⎦⎠  ⎝        ⎣⎣ 1 ⎦⎦⎠⎦

In [41]:
v1 = Matrix([sym.Rational(3,4),1])
v2 =  Matrix([sym.Rational(-4,3),1])
v1 = v1/v1.norm()
v2 = v2/v2.norm()
V = Matrix([v1.T,v2.T]).T
U1= V

In [42]:
V = Matrix([[0,1],[1,0]])
W = sym.diag(10,5)
U=(A*V*W.inv())
U, U.n(2)
U *U1


⎡-1  0⎤
⎢     ⎥
⎣0   1⎦

In [8]:
a= np.array(A).astype(np.float64)

u,s,vh = np.linalg.svd(a,full_matrices=False)
u,s,vh.transpose()

(array([[ 0.6, -0.8],
        [ 0.8,  0.6]]),
 array([10.,  5.]),
 array([[-0.,  1.],
        [-1.,  0.]]))

### P4. Below is a singular value decomposition of a matrix $A$:
#### $A=\begin{bmatrix} -\frac{1}{\sqrt{5}}&-\frac{1}{\sqrt{5}}\\ -\frac{2}{\sqrt{5}}&-\frac{1}{\sqrt{5}}    \end{bmatrix} \begin{bmatrix}\sqrt{15}&0&0\\0&0&0 \end{bmatrix}  \begin{bmatrix}-\frac{1}{\sqrt{3}}&\frac{1}{\sqrt{3}}&-\frac{1}{\sqrt{3}}\\ -\frac{2}{\sqrt{6}}&-\frac{1}{\sqrt{6}}&\frac{1}{\sqrt{6}}\\ 0&\frac{1}{\sqrt{2}} &\frac{1}{\sqrt{2}}      \end{bmatrix}$

In [9]:
U = 1/sym.sqrt(5) * Matrix([[-1,-2], [2,-1]])
W = Matrix([[sym.sqrt(15),0,0],[0,0,0]])
VT = Matrix([[-1/sym.sqrt(3),1/sym.sqrt(3),-1/sym.sqrt(3)],\
             [-2/sym.sqrt(6),-1/sym.sqrt(6),1/sym.sqrt(6)],\
             [0,1/sym.sqrt(2),1/sym.sqrt(2)]])
U,W,VT

⎛                             ⎡-√3    √3   -√3 ⎤⎞
⎜                             ⎢────   ──   ────⎥⎟
⎜⎡-√5   -2⋅√5 ⎤               ⎢ 3     3     3  ⎥⎟
⎜⎢────  ──────⎥               ⎢                ⎥⎟
⎜⎢ 5      5   ⎥  ⎡√15  0  0⎤  ⎢-√6   -√6    √6 ⎥⎟
⎜⎢            ⎥, ⎢         ⎥, ⎢────  ────   ── ⎥⎟
⎜⎢2⋅√5   -√5  ⎥  ⎣ 0   0  0⎦  ⎢ 3     6     6  ⎥⎟
⎜⎢────   ──── ⎥               ⎢                ⎥⎟
⎜⎣ 5      5   ⎦               ⎢       √2    √2 ⎥⎟
⎜                             ⎢ 0     ──    ── ⎥⎟
⎝                             ⎣       2     2  ⎦⎠

#### a) What is rank $A$?

In [10]:
W.rank()

#### b) Let $b=\begin{bmatrix}3\\4\end{bmatrix}$.  Find the pseduo-inverse of $A$, i.e. $A^{\dagger}$, and the minimal length least-squares solution for $Ax=b$.

In [11]:
# b) psuedo-inverse of A, Ai = Vr D^-1 UrT
b= Matrix([3,4])
V = VT.transpose()
Ai = V.col(0)* Matrix([W[0]]).inv()*  U.col(0).T
Ai, U*W*VT, V.col(0), Matrix([W[0]]).inv(),  U.col(0).T, Ai * b

⎛                              ⎡-√3 ⎤                             ⎞
⎜                              ⎢────⎥                             ⎟
⎜                              ⎢ 3  ⎥                             ⎟
⎜⎡1/15   -2/15⎤                ⎢    ⎥                       ⎡-1/3⎤⎟
⎜⎢            ⎥  ⎡1   -1  1 ⎤  ⎢ √3 ⎥  ⎡√15⎤  ⎡-√5   2⋅√5⎤  ⎢    ⎥⎟
⎜⎢-1/15  2/15 ⎥, ⎢          ⎥, ⎢ ── ⎥, ⎢───⎥, ⎢────  ────⎥, ⎢1/3 ⎥⎟
⎜⎢            ⎥  ⎣-2  2   -2⎦  ⎢ 3  ⎥  ⎣ 15⎦  ⎣ 5     5  ⎦  ⎢    ⎥⎟
⎜⎣1/15   -2/15⎦                ⎢    ⎥                       ⎣-1/3⎦⎟
⎜                              ⎢-√3 ⎥                             ⎟
⎜                              ⎢────⎥                             ⎟
⎝                              ⎣ 3  ⎦                             ⎠

#### c) Find the projection of $\begin{bmatrix}1\\1\\1\end{bmatrix}$ onto the nullspace of $A$.

In [12]:
# c) project onto nullA
f = Matrix([1,1,1])
A =  U*W*VT
A, A.nullspace() # note nullA is {Vr+1,...,Vn}

Vn = Matrix([(V.col(1)/V.col(1).norm()).T , (V.col(2)/V.col(2).norm()).T]).T
Vn*Vn.T * f

⎡2/3⎤
⎢   ⎥
⎢4/3⎥
⎢   ⎥
⎣2/3⎦

### Appendix 1. 